Fix skipping, add db dumps to artifacts

diff --git a/.github/workflows/e2e.yaml b/.github/workflows/e2e.yaml
--- a/.github/workflows/e2e.yaml
+++ b/.github/workflows/e2e.yaml
@@ -212,6 +212,7 @@ jobs:
           exit 1
 
       - name: Run Cypress tests
+        continue-on-error: true
         run: |
           mkdir -p cypress
           npx cypress run \
@@ -290,6 +291,7 @@ jobs:
             cypress/screenshots
             cypress/videos
             cypress/downloads
+            cypress/artifacts/db-dumps
             web-api.log
             grader-mock.log
           if-no-files-found: ignore
@@ -384,3 +386,11 @@ jobs:
                 body,
               });
             }
+
+      - name: Fail job if Cypress failed
+        if: always()
+        run: |
+          if grep -q '"failures":[1-9]' cypress/results.json; then
+            echo "Cypress tests failed"
+            exit 1
+          fi
